language: node_js
node_js:
  - '14'

cache:
  directories:
    - node_modules
    - $HOME/.local

notifications:
  email: false

jobs:
  include:
    - stage: Linting & Formatting
      name: Linting
      install:
        - make install
      script:
        - make linters pretty

    - stage: Tests
      name: Unit Tests
      script:
        - make unit_test
    - name: Integration Tests
      install:
        - make ci_setup install
      services:
        - docker
      env:
        - AWS_COMMAND=/home/travis/.local/lib/aws/bin/aws
      script:
        - make run integration_test
