---
routes:
  /v1/animal:
    backend: "https://animal.ionchannel.testing:4567"
  /v1/product:
    backend: "http://bunsen:4567"
  /v1/vulnerability:
    backend: "http://bunsen:4567"
  /v1/accountUsers:
    backend: "http://janice:4567"
  /v1/accounts:
    backend: "http://janice:4567"
  /v1/auth:
    backend: "http://janice:4567"
  /v1/dev/createInviteToken:
    backend: "http://janice:4567"
  /v1/sessions:
    backend: "http://janice:4567"
  /v1/teamUsers:
    backend: "http://janice:4567"
  /v1/teams:
    backend: "http://janice:4567"
  /v1/tokens:
    backend: "http://janice:4567"
  /v1/users:
    backend: "http://janice:4567"
  /v1/airgap:
    backend: "http://kermit:4567"
  /v1/scanner:
    backend: "http://kermit:4567"
  /v1/search:
    backend: "http://rosita:4567"
  /v1/report:
    backend: "https://statler.ionchannel.testing:4567"
  /v1/ruleset:
    backend: "http://waldorf:4567"
  /v1/project:
    backend: "https://yolanda.ionchannel.testing:4567"
ca: |
  -----BEGIN CERTIFICATE-----
  MIID1jCCAr4CCQDGAR2EiTGzkTANBgkqhkiG9w0BAQUFADCBrDELMAkGA1UEBhMC
  VVMxCzAJBgNVBAgMAlZBMRgwFgYDVQQHDA9Jb25DaGFubmVsIENpdHkxFDASBgNV
  BAoMC0lvbiBDaGFubmVsMRkwFwYDVQQLDBBJb24gQ2hhbm5lbCBQcm9kMSEwHwYD
  VQQDDBhQcm9kIElvbiBDaGFubmVsIFJvb3QgQ0ExIjAgBgkqhkiG9w0BCQEWE2Fk
  bWluQGlvbmNoYW5uZWwuaW8wHhcNMTkwOTA1MjMxMjQxWhcNMjkwOTAyMjMxMjQx
  WjCBrDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMRgwFgYDVQQHDA9Jb25DaGFu
  bmVsIENpdHkxFDASBgNVBAoMC0lvbiBDaGFubmVsMRkwFwYDVQQLDBBJb24gQ2hh
  bm5lbCBQcm9kMSEwHwYDVQQDDBhQcm9kIElvbiBDaGFubmVsIFJvb3QgQ0ExIjAg
  BgkqhkiG9w0BCQEWE2FkbWluQGlvbmNoYW5uZWwuaW8wggEiMA0GCSqGSIb3DQEB
  AQUAA4IBDwAwggEKAoIBAQCjRtozrWLr1YkOUZbbauL0KK5vi5Ns75YzFftZW/Re
  az7hJ94FlHAEFQBve3uAycsS3ysj5gifbnGHtn6j5OHtIW7ce9AwYOXfGTwUqeKo
  j38vlQEwrjW/q+uq69jo00fs0bNaX4wnVVvmKwi/KPJowBaBvb4RWfs5PcJhu3B7
  sSXrlteOMiz6ruJCC7uyhLdWFxJeLS1XyZ7kkOX/DAeiKcjWzU88D80OmSPm1qeX
  7TPbMbfSiSOA9KjKz61f+cmo2LofaZs4x6XCLFvi3N6JnV/HjaXaXUzSBn6X+jqQ
  9xtCwb6Vj/UeVMPwGW6OD5asslenRPF9Deue248Pa0+BAgMBAAEwDQYJKoZIhvcN
  AQEFBQADggEBAGUZZW1bidYvPnM9HwDPKlDnfgCfEUbhklbk8KwYsGSZstOdDTm9
  O9RMO7KILEquhIXrVCFuBiK7jV5yMokM/x0ENCan0iqhSCEn45v0rZN+jjYfh7RP
  8h0T8kRow36fNRxYaj5b2rUlUWicarJam9fmUJIF/Xa5Yy6Zl/6f6ks1wWkyyjgC
  4FH9QNZRRzN/IEh8V48akXUCauuLjXE4EmTK7jZLNg0CeJmo2qUa3D267KXEmseW
  xaqx43EBA+6Mkjer/oiEvtE/AS+tmmW4EW/PrtTdqfMGmDYN/TbVEkQDrLJjuafH
  UkoDNnU0yUPw3bQMRGBl8oo9weXz14OMNvg=
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIDxDCCAqwCCQDmvKEybk2dNzANBgkqhkiG9w0BAQUFADCBozELMAkGA1UEBhMC
  VVMxCzAJBgNVBAgMAlZBMRcwFQYDVQQHDA5Jb25DaGFubmVsQ2l0eTETMBEGA1UE
  CgwKSW9uQ2hhbm5lbDEcMBoGA1UECwwTSW9uIENoYW5uZWwgVGVzdGluZzEXMBUG
  A1UEAwwOSW9uIENoYW5uZWwgQ0ExIjAgBgkqhkiG9w0BCQEWE2FkbWluQGlvbmNo
  YW5uZWwuaW8wHhcNMTkwOTA1MjI0NTQzWhcNMjkwOTAyMjI0NTQzWjCBozELMAkG
  A1UEBhMCVVMxCzAJBgNVBAgMAlZBMRcwFQYDVQQHDA5Jb25DaGFubmVsQ2l0eTET
  MBEGA1UECgwKSW9uQ2hhbm5lbDEcMBoGA1UECwwTSW9uIENoYW5uZWwgVGVzdGlu
  ZzEXMBUGA1UEAwwOSW9uIENoYW5uZWwgQ0ExIjAgBgkqhkiG9w0BCQEWE2FkbWlu
  QGlvbmNoYW5uZWwuaW8wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC1
  k2JgJJxo+pC5xj7sVvBiGBJhnkZglFTsXJhjMpx2kbr1RPG4UgjwdW9He5MEcis+
  jSz3+/3lLOMuX/p5v1TK64cR39DuuBkqaTLEBtl62tOhMZbyKbhXGEvV1fhzup7x
  zkTPzmH+T5iMCfXjjC3GDxj/6KepZGpXBaqZj4BsRBd3+ahcpWcOFlufRJf8jJwP
  8aXpQtsED/6C4gff+rRhvn03y6OxiJjGCM/hu4NAWuvdfPugcc4uFru2UL78qX+u
  2JM+I7RRAzc+bFn10lCh2IzorQfw26o7yOhWw11Oshx9PFKEcbYl5OGSEbDM8q00
  F352HS6cvZE//HZApRANAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAJ8E0+kvSGvV
  clYx59i0Cc3P/4IwllA8P+iLeigYIc67itcouqLUM1ePgl3uXw8IEU7zECdkOVue
  cchlXa9SdRPm+JhD2XQh8SUln3i7bRy13n29t602LMwqALS/9lW+M+SwLYDkVb2x
  MZ+N+S6sGo9jYeLsrIIzQpF9rthWUYwDWqApNPR6dT9mGZexPzZ10BtGuJqsp9xt
  YextOhjP2OFp6CEEKFHPlwtpra3h+KdiTIgOU4WApt5PCft/BD5Mp0XdxLZSRc+P
  hIJqNdIWksuW6NCbaaA9wrSEJQLkhvMxJ52y/8cGglznaXjjB1a53SMHCBlo272u
  hTNmzTHvO6o=
  -----END CERTIFICATE-----
