version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/anion
    steps:
      - checkout
      - run:
          name: Setup environmemnt
          command: make ci_setup
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Yarn Install
          command: make install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run ci
          command: make ci

  lint:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/anion
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Linting
          command: make linters

  test:
    docker:
      - image: circleci/node:10.12.0
    working_directory: ~/anion
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run services
          command: make run
      - run:
          name: Tests
          command: make test


workflows:
  version: 2
  build_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
